# Generated by Django 2.1.5 on 2019-02-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendaClub', '0002_auto_20190208_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
    ]
