# Generated by Django 2.1.5 on 2019-02-08 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendaClub', '0003_auto_20190208_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=400, validators=[django.core.validators.MaxLengthValidator(400)]),
        ),
    ]
